# Exported from Render on 2024-05-28T12:46:34Z
services:
- type: web
  name: blog
  runtime: docker
  repo: https://github.com/reddevx/blog
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"