default: &default
  adapter: postgresql
  encoding: unicode
  pool: 3

development:
  <<: *default
  database: nome_do_banco_de_dados
  username: reddevx
  password: root
  host: localhost
  port: 5432