default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog
  username: root
  password: root
  host: localhost

production:
  <<: *default
  database: postgres://postgres:5Z63WfG3LCUAAD8@lazuli-app-hack.flycast:5432
  username: postgres
  password: 5Z63WfG3LCUAAD8
  host: https://lazuli-hackzz.fly.dev/