default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog
  username: root
  password: root
  host: localhost

production:
  <<: *default
  database: blog
  username: root
  password: root
  host: localhost
